name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

jobs:

  compilejobWIN:
    runs-on: windows-latest
    name: WINFORTRAN_on_WIN
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
          Invoke-WebRequest https://www.ftn95.co.uk/ftn95/ftn95-8.95/ftn95_personal.exe -O ftn95_personal.exe
    - name: Compile
      run: |
          ftn95_personal.exe main.f

